"""Multilingual educational content. Languages: en, hi, zh, es, ja, pt"""

PLANET_EDUCATION = {
  'en': {
    'Sun': {'significance': 'Soul, ego, vitality, father, authority, heart, bones', 'nature': 'The king. Your core identity — who you are when no one is watching.', 'strong': 'Natural authority. People listen without being asked.', 'weak': 'Confidence wavers. You feel unseen. Heart and bones need attention.', 'day': 'Sunday', 'gem': 'Ruby', 'color': 'Deep red'},
    'Moon': {'significance': 'Mind, emotions, mother, public image, sleep, chest', 'nature': 'The queen. Your inner landscape — emotional body, instincts, comfort.', 'strong': 'Mind calm and receptive. Emotional intelligence high. Sleep deep.', 'weak': 'Mind restless. Anxiety, overthinking, emotional volatility.', 'day': 'Monday', 'gem': 'Pearl', 'color': 'White'},
    'Mars': {'significance': 'Courage, energy, siblings, property, sports, blood, muscles', 'nature': 'The commander. Raw energy, physical courage, drive to act.', 'strong': 'Vital, decisive, brave. Property matters favor you.', 'weak': 'Anger turns inward or explodes. Accidents more likely.', 'day': 'Tuesday', 'gem': 'Red Coral', 'color': 'Red'},
    'Mercury': {'significance': 'Intelligence, speech, commerce, writing, skin, nerves', 'nature': 'The prince. Communication, analytical thinking, adaptability.', 'strong': 'Speech precise and persuasive. Business acumen sharp.', 'weak': 'Communication misfires. Misunderstandings multiply.', 'day': 'Wednesday', 'gem': 'Emerald', 'color': 'Green'},
    'Jupiter': {'significance': 'Wisdom, expansion, children, teachers, dharma, wealth', 'nature': 'The guru. Most benefic. Wisdom, teachers, divine grace.', 'strong': 'Wisdom flows naturally. Teachers appear at the right time.', 'weak': 'Judgment falters. Wrong teachers. Financial decisions lack wisdom.', 'day': 'Thursday', 'gem': 'Yellow Sapphire', 'color': 'Yellow'},
    'Venus': {'significance': 'Love, beauty, marriage, luxury, art, vehicles, kidneys', 'nature': 'The minister. Desire, attraction, beauty, creative expression.', 'strong': 'Love comes naturally. Relationships carry harmony.', 'weak': 'Relationships suffer imbalance. Creative expression blocked.', 'day': 'Friday', 'gem': 'Diamond', 'color': 'White'},
    'Saturn': {'significance': 'Discipline, karma, longevity, chronic illness, delays, bones', 'nature': 'The judge. Teaches through pressure. Where you must work hardest.', 'strong': 'Discipline natural. You endure what others cannot.', 'weak': 'Delays unbearable. Chronic health issues. Work unrewarded.', 'day': 'Saturday', 'gem': 'Blue Sapphire', 'color': 'Dark blue'},
    'Rahu': {'significance': 'Obsession, illusion, foreign lands, technology, sudden events', 'nature': 'The shadow. Amplifies whatever it touches — hunger, ambition.', 'strong': 'Extraordinary worldly success. Foreign connections thrive.', 'weak': 'Confusion, addiction, illusion.', 'day': 'Saturday', 'gem': 'Hessonite', 'color': 'Smoky'},
    'Ketu': {'significance': 'Liberation, past lives, detachment, spiritual insight, psychic ability', 'nature': 'The headless one. Dissolves what Rahu craves.', 'strong': 'Deep spiritual insight, psychic sensitivity, ability to let go.', 'weak': 'Emptiness, confusion about identity, sudden losses.', 'day': 'Tuesday', 'gem': "Cat's Eye", 'color': 'Grey'},
  },
  'hi': {
    'Sun': {'significance': 'आत्मा, अहंकार, जीवनशक्ति, पिता, अधिकार, हृदय, हड्डियाँ', 'nature': 'राजा। आपकी मूल पहचान — जब कोई नहीं देख रहा, तब आप कौन हैं।', 'strong': 'स्वाभाविक अधिकार। लोग बिना कहे सुनते हैं।', 'weak': 'आत्मविश्वास डगमगाता है। अनदेखा महसूस होता है।', 'day': 'रविवार', 'gem': 'माणिक', 'color': 'गहरा लाल'},
    'Moon': {'significance': 'मन, भावनाएँ, माता, सार्वजनिक छवि, नींद, छाती', 'nature': 'रानी। आंतरिक संसार — भावनात्मक शरीर, सहज ज्ञान, सुकून।', 'strong': 'मन शांत और ग्रहणशील। भावनात्मक बुद्धि उच्च।', 'weak': 'मन बेचैन। चिंता, अत्यधिक सोचना, भावनात्मक अस्थिरता।', 'day': 'सोमवार', 'gem': 'मोती', 'color': 'सफ़ेद'},
    'Mars': {'significance': 'साहस, ऊर्जा, भाई-बहन, संपत्ति, खेल, रक्त, मांसपेशियाँ', 'nature': 'सेनापति। कच्ची ऊर्जा, शारीरिक साहस, कर्म की प्रेरणा।', 'strong': 'शारीरिक रूप से सशक्त, निर्णायक, बहादुर।', 'weak': 'क्रोध अंदर घुटता है या फूटता है। दुर्घटनाएँ संभव।', 'day': 'मंगलवार', 'gem': 'मूँगा', 'color': 'लाल'},
    'Mercury': {'significance': 'बुद्धि, वाणी, व्यापार, लेखन, त्वचा, तंत्रिका तंत्र', 'nature': 'राजकुमार। संवाद, विश्लेषणात्मक सोच, अनुकूलन क्षमता।', 'strong': 'वाणी सटीक और प्रभावशाली। व्यापारिक सूझबूझ तेज।', 'weak': 'संवाद बिगड़ता है। गलतफहमियाँ बढ़ती हैं।', 'day': 'बुधवार', 'gem': 'पन्ना', 'color': 'हरा'},
    'Jupiter': {'significance': 'ज्ञान, विस्तार, संतान, गुरु, धर्म, धन, अध्यात्म', 'nature': 'गुरु। सबसे शुभ ग्रह। ज्ञान, शिक्षकों और दैवी कृपा।', 'strong': 'ज्ञान स्वाभाविक। सही समय पर गुरु मिलते हैं।', 'weak': 'निर्णय डगमगाता है। गलत गुरु। आर्थिक बुद्धि की कमी।', 'day': 'गुरुवार', 'gem': 'पुखराज', 'color': 'पीला'},
    'Venus': {'significance': 'प्रेम, सौंदर्य, विवाह, विलासिता, कला, वाहन, गुर्दे', 'nature': 'मंत्री। इच्छा, आकर्षण, सौंदर्य, रचनात्मक अभिव्यक्ति।', 'strong': 'प्रेम सहज। रिश्तों में सामंजस्य। कला खिलती है।', 'weak': 'रिश्तों में असंतुलन। रचनात्मक अभिव्यक्ति अवरुद्ध।', 'day': 'शुक्रवार', 'gem': 'हीरा', 'color': 'सफ़ेद'},
    'Saturn': {'significance': 'अनुशासन, कर्म, दीर्घायु, पुरानी बीमारी, देरी, हड्डियाँ', 'nature': 'न्यायाधीश। दबाव से सिखाता है। जहाँ सबसे कठिन मेहनत करनी है।', 'strong': 'अनुशासन स्वाभाविक। जो दूसरे नहीं सह सकते, आप सहते हैं।', 'weak': 'देरी असहनीय। पुरानी स्वास्थ्य समस्याएँ। मेहनत का फल नहीं।', 'day': 'शनिवार', 'gem': 'नीलम', 'color': 'गहरा नीला'},
    'Rahu': {'significance': 'जुनून, माया, विदेश, तकनीक, अपारंपरिक मार्ग', 'nature': 'छाया। जो छूता है उसे बढ़ाता है — भूख, महत्वाकांक्षा।', 'strong': 'असाधारण सांसारिक सफलता। विदेशी संबंध फलते हैं।', 'weak': 'भ्रम, लत, माया। पकड़ते ही गायब।', 'day': 'शनिवार', 'gem': 'गोमेद', 'color': 'धुँधला'},
    'Ketu': {'significance': 'मोक्ष, पूर्वजन्म, वैराग्य, आध्यात्मिक अंतर्दृष्टि', 'nature': 'बिना सिर का। राहु जो चाहता है उसे विलीन करता है।', 'strong': 'गहरी आध्यात्मिक अंतर्दृष्टि, छोड़ने की कला।', 'weak': 'खालीपन, पहचान का भ्रम, अचानक हानि।', 'day': 'मंगलवार', 'gem': 'लहसुनिया', 'color': 'धूसर'},
  },
  'es': {
    'Sun': {'significance': 'Alma, ego, vitalidad, padre, autoridad, corazón, huesos', 'nature': 'El rey. Tu identidad esencial — quién eres cuando nadie mira.', 'strong': 'Autoridad natural. La gente escucha sin que lo pidas.', 'weak': 'La confianza vacila. Te sientes invisible.', 'day': 'Domingo', 'gem': 'Rubí', 'color': 'Rojo profundo'},
    'Moon': {'significance': 'Mente, emociones, madre, imagen pública, sueño', 'nature': 'La reina. Tu paisaje interior — cuerpo emocional, instintos.', 'strong': 'Mente tranquila y receptiva. Inteligencia emocional alta.', 'weak': 'Mente inquieta. Ansiedad, pensar en exceso.', 'day': 'Lunes', 'gem': 'Perla', 'color': 'Blanco'},
    'Mars': {'significance': 'Coraje, energía, hermanos, propiedad, deportes, sangre', 'nature': 'El comandante. Energía cruda, coraje físico.', 'strong': 'Vital, decisivo, valiente.', 'weak': 'La ira explota. Accidentes más probables.', 'day': 'Martes', 'gem': 'Coral rojo', 'color': 'Rojo'},
    'Mercury': {'significance': 'Inteligencia, habla, comercio, escritura, piel, nervios', 'nature': 'El príncipe. Comunicación, pensamiento analítico.', 'strong': 'Habla precisa y persuasiva. Agudeza comercial.', 'weak': 'La comunicación falla. Malentendidos.', 'day': 'Miércoles', 'gem': 'Esmeralda', 'color': 'Verde'},
    'Jupiter': {'significance': 'Sabiduría, expansión, hijos, maestros, dharma, riqueza', 'nature': 'El gurú. Planeta más benéfico. Sabiduría y gracia divina.', 'strong': 'La sabiduría fluye. Maestros en el momento justo.', 'weak': 'El juicio falla. Maestros equivocados.', 'day': 'Jueves', 'gem': 'Zafiro amarillo', 'color': 'Amarillo'},
    'Venus': {'significance': 'Amor, belleza, matrimonio, lujo, arte, vehículos', 'nature': 'El ministro. Deseo, atracción, belleza, expresión creativa.', 'strong': 'El amor viene naturalmente. Armonía en relaciones.', 'weak': 'Relaciones desequilibradas. Expresión creativa bloqueada.', 'day': 'Viernes', 'gem': 'Diamante', 'color': 'Blanco'},
    'Saturn': {'significance': 'Disciplina, karma, longevidad, enfermedad crónica, retrasos', 'nature': 'El juez. Enseña a través de presión.', 'strong': 'Disciplina natural. Resistes lo que otros no pueden.', 'weak': 'Retrasos insoportables. Problemas crónicos.', 'day': 'Sábado', 'gem': 'Zafiro azul', 'color': 'Azul oscuro'},
    'Rahu': {'significance': 'Obsesión, ilusión, tierras extranjeras, tecnología', 'nature': 'La sombra. Amplifica todo — hambre, ambición, obsesión.', 'strong': 'Éxito mundano extraordinario.', 'weak': 'Confusión, adicción, ilusión.', 'day': 'Sábado', 'gem': 'Hesonita', 'color': 'Ahumado'},
    'Ketu': {'significance': 'Liberación, vidas pasadas, desapego, intuición espiritual', 'nature': 'El sin cabeza. Disuelve lo que Rahu ansía.', 'strong': 'Profunda intuición espiritual, capacidad de soltar.', 'weak': 'Vacío, confusión, pérdidas repentinas.', 'day': 'Martes', 'gem': 'Ojo de gato', 'color': 'Gris'},
  },
  'zh': {
    'Sun': {'significance': '灵魂、自我、活力、父亲、权威、心脏、骨骼', 'nature': '王。核心身份——无人注视时的你。', 'strong': '天生权威。不必开口，人们自然倾听。', 'weak': '信心动摇。感觉被忽视。', 'day': '周日', 'gem': '红宝石', 'color': '深红'},
    'Moon': {'significance': '心灵、情感、母亲、公众形象、睡眠', 'nature': '女王。内在世界——情感体、直觉、安适。', 'strong': '心灵平静敏锐。情商极高。睡眠深沉。', 'weak': '心灵不安。焦虑、过度思考。', 'day': '周一', 'gem': '珍珠', 'color': '白色'},
    'Mars': {'significance': '勇气、能量、兄弟姐妹、财产、运动、血液', 'nature': '统帅。原始能量，身体勇气。', 'strong': '充满活力，果断，勇敢。', 'weak': '愤怒内化或爆发。事故更可能。', 'day': '周二', 'gem': '红珊瑚', 'color': '红色'},
    'Mercury': {'significance': '智慧、言语、商业、写作、皮肤、神经系统', 'nature': '王子。沟通、分析思维、适应力。', 'strong': '言辞精准。商业头脑敏锐。', 'weak': '沟通出错。误解倍增。', 'day': '周三', 'gem': '祖母绿', 'color': '绿色'},
    'Jupiter': {'significance': '智慧、扩展、子女、老师、正法、财富', 'nature': '导师。最吉祥行星。智慧与神恩。', 'strong': '智慧自然流动。老师适时出现。', 'weak': '判断力下降。错误的老师。', 'day': '周四', 'gem': '黄色蓝宝石', 'color': '黄色'},
    'Venus': {'significance': '爱情、美丽、婚姻、奢华、艺术', 'nature': '大臣。欲望、吸引力、美丽。', 'strong': '爱情自然而来。关系和谐。', 'weak': '关系失衡。创意受阻。', 'day': '周五', 'gem': '钻石', 'color': '白色'},
    'Saturn': {'significance': '纪律、业力、长寿、慢性病、延迟、骨骼', 'nature': '法官。通过压力教导。', 'strong': '纪律是天性。忍受他人不能承受之事。', 'weak': '延迟难以忍受。慢性健康问题。', 'day': '周六', 'gem': '蓝宝石', 'color': '深蓝'},
    'Rahu': {'significance': '执念、幻象、异国、科技、突发事件', 'nature': '暗影。放大一切——饥渴、野心。', 'strong': '非凡世俗成功。海外关系蓬勃。', 'weak': '困惑、上瘾、幻觉。', 'day': '周六', 'gem': '橙榴石', 'color': '烟色'},
    'Ketu': {'significance': '解脱、前世、超然、灵性洞察', 'nature': '无头者。溶解拉胡渴望之物。', 'strong': '深邃灵性洞察，从容放下。', 'weak': '空虚，身份困惑，突然失去。', 'day': '周二', 'gem': '猫眼石', 'color': '灰色'},
  },
  'ja': {
    'Sun': {'significance': '魂、自我、活力、父、権威、心臓、骨', 'nature': '王。核心のアイデンティティ。', 'strong': '生まれながらの権威。求めずとも人が聞く。', 'weak': '自信が揺らぐ。見過ごされる。', 'day': '日曜日', 'gem': 'ルビー', 'color': '深紅'},
    'Moon': {'significance': '心、感情、母、公的イメージ、睡眠', 'nature': '女王。内面の風景——感情体、直感。', 'strong': '心穏やか。感情知性が高い。', 'weak': '心が落ち着かない。不安、考えすぎ。', 'day': '月曜日', 'gem': '真珠', 'color': '白'},
    'Mars': {'significance': '勇気、エネルギー、兄弟、不動産、スポーツ', 'nature': '司令官。生のエネルギー、身体的勇気。', 'strong': '活力、決断力、勇敢。', 'weak': '怒りが内に向かうか爆発。', 'day': '火曜日', 'gem': '赤珊瑚', 'color': '赤'},
    'Mercury': {'significance': '知性、話術、商業、文筆、皮膚、神経系', 'nature': '王子。コミュニケーション、分析的思考。', 'strong': '話術は正確で説得力がある。', 'weak': 'コミュニケーションが失敗。誤解が増える。', 'day': '水曜日', 'gem': 'エメラルド', 'color': '緑'},
    'Jupiter': {'significance': '知恵、拡大、子供、師、ダルマ、富', 'nature': '導師。最も吉祥な惑星。', 'strong': '知恵が自然に流れる。適切な時に師が現れる。', 'weak': '判断力が鈍る。間違った師。', 'day': '木曜日', 'gem': 'イエローサファイア', 'color': '黄'},
    'Venus': {'significance': '愛、美、結婚、贅沢、芸術', 'nature': '大臣。欲望、魅力、美、創造的表現。', 'strong': '愛が自然に訪れる。関係に調和。', 'weak': '関係にアンバランス。', 'day': '金曜日', 'gem': 'ダイヤモンド', 'color': '白'},
    'Saturn': {'significance': '規律、カルマ、長寿、慢性疾患、遅延、骨', 'nature': '裁判官。圧力を通じて教える。', 'strong': '規律は天性。他者が耐えられないことに耐える。', 'weak': '遅延に耐えられない。慢性的な健康問題。', 'day': '土曜日', 'gem': 'ブルーサファイア', 'color': '濃紺'},
    'Rahu': {'significance': '執着、幻想、外国、テクノロジー', 'nature': '影。触れるもの全てを増幅。', 'strong': '並外れた世俗的成功。', 'weak': '混乱、依存、幻想。', 'day': '土曜日', 'gem': 'ヘソナイト', 'color': '煙色'},
    'Ketu': {'significance': '解脱、前世、離欲、霊的洞察', 'nature': '首のない者。ラーフが渇望するものを溶かす。', 'strong': '深い霊的洞察、手放す力。', 'weak': '空虚、突然の喪失。', 'day': '火曜日', 'gem': 'キャッツアイ', 'color': '灰色'},
  },
  'pt': {
    'Sun': {'significance': 'Alma, ego, vitalidade, pai, autoridade, coração, ossos', 'nature': 'O rei. Sua identidade essencial.', 'strong': 'Autoridade natural. As pessoas ouvem sem ser pedido.', 'weak': 'A confiança vacila. Você se sente invisível.', 'day': 'Domingo', 'gem': 'Rubi', 'color': 'Vermelho profundo'},
    'Moon': {'significance': 'Mente, emoções, mãe, imagem pública, sono', 'nature': 'A rainha. Paisagem interior — corpo emocional, instintos.', 'strong': 'Mente calma e receptiva. Inteligência emocional alta.', 'weak': 'Mente inquieta. Ansiedade, excesso de pensamento.', 'day': 'Segunda', 'gem': 'Pérola', 'color': 'Branco'},
    'Mars': {'significance': 'Coragem, energia, irmãos, propriedade, esportes, sangue', 'nature': 'O comandante. Energia bruta, coragem física.', 'strong': 'Vital, decisivo, corajoso.', 'weak': 'A raiva explode. Acidentes mais prováveis.', 'day': 'Terça', 'gem': 'Coral vermelho', 'color': 'Vermelho'},
    'Mercury': {'significance': 'Inteligência, fala, comércio, escrita, pele, nervos', 'nature': 'O príncipe. Comunicação, pensamento analítico.', 'strong': 'Fala precisa e persuasiva.', 'weak': 'Comunicação falha. Mal-entendidos.', 'day': 'Quarta', 'gem': 'Esmeralda', 'color': 'Verde'},
    'Jupiter': {'significance': 'Sabedoria, expansão, filhos, mestres, dharma, riqueza', 'nature': 'O guru. Planeta mais benéfico.', 'strong': 'Sabedoria flui. Mestres no momento certo.', 'weak': 'Julgamento falha. Mestres errados.', 'day': 'Quinta', 'gem': 'Safira amarela', 'color': 'Amarelo'},
    'Venus': {'significance': 'Amor, beleza, casamento, luxo, arte', 'nature': 'O ministro. Desejo, atração, beleza.', 'strong': 'Amor vem naturalmente. Harmonia nos relacionamentos.', 'weak': 'Relacionamentos desequilibrados.', 'day': 'Sexta', 'gem': 'Diamante', 'color': 'Branco'},
    'Saturn': {'significance': 'Disciplina, karma, longevidade, doença crônica, atrasos', 'nature': 'O juiz. Ensina através da pressão.', 'strong': 'Disciplina natural. Suporta o que outros não conseguem.', 'weak': 'Atrasos insuportáveis. Problemas crônicos.', 'day': 'Sábado', 'gem': 'Safira azul', 'color': 'Azul escuro'},
    'Rahu': {'significance': 'Obsessão, ilusão, terras estrangeiras, tecnologia', 'nature': 'A sombra. Amplifica tudo que toca.', 'strong': 'Sucesso mundano extraordinário.', 'weak': 'Confusão, vício, ilusão.', 'day': 'Sábado', 'gem': 'Hessonita', 'color': 'Esfumaçado'},
    'Ketu': {'significance': 'Libertação, vidas passadas, desapego, intuição espiritual', 'nature': 'O sem cabeça. Dissolve o que Rahu deseja.', 'strong': 'Profunda intuição espiritual, desapegar.', 'weak': 'Vazio, confusão, perdas repentinas.', 'day': 'Terça', 'gem': 'Olho de gato', 'color': 'Cinza'},
  },
}

HOUSE_ED = {
  'en': {1:('Ascendant','Self, body, identity'),2:('Wealth','Money, speech, family'),3:('Courage','Siblings, courage, effort'),4:('Home','Mother, home, peace'),5:('Intelligence','Children, creativity, past merit'),6:('Conflict','Enemies, disease, service'),7:('Partnership','Marriage, business partners'),8:('Transformation','Death, rebirth, hidden wealth'),9:('Fortune','Father, guru, luck'),10:('Career','Profession, status, public action'),11:('Gains','Income, friends, aspirations'),12:('Liberation','Loss, isolation, moksha')},
  'hi': {1:('लग्न','आत्म, शरीर, पहचान'),2:('धन','पैसा, वाणी, परिवार'),3:('साहस','भाई-बहन, साहस, प्रयास'),4:('सुख','माता, घर, शांति'),5:('बुद्धि','संतान, रचनात्मकता, पूर्व पुण्य'),6:('शत्रु','दुश्मन, रोग, सेवा'),7:('साझेदारी','विवाह, व्यापारिक साझेदार'),8:('रूपांतर','मृत्यु, पुनर्जन्म, छिपा धन'),9:('भाग्य','पिता, गुरु, भाग्य'),10:('कर्म','पेशा, प्रतिष्ठा, सार्वजनिक कर्म'),11:('लाभ','आय, मित्र, आकांक्षाएँ'),12:('मोक्ष','हानि, एकांत, मुक्ति')},
  'es': {1:('Ascendente','Yo, cuerpo, identidad'),2:('Riqueza','Dinero, habla, familia'),3:('Coraje','Hermanos, coraje, esfuerzo'),4:('Hogar','Madre, hogar, paz'),5:('Inteligencia','Hijos, creatividad'),6:('Conflicto','Enemigos, enfermedad'),7:('Pareja','Matrimonio, socios'),8:('Transformación','Muerte, renacimiento'),9:('Fortuna','Padre, gurú, suerte'),10:('Carrera','Profesión, estatus'),11:('Ganancias','Ingresos, amigos'),12:('Liberación','Pérdida, aislamiento')},
  'pt': {1:('Ascendente','Eu, corpo, identidade'),2:('Riqueza','Dinheiro, fala, família'),3:('Coragem','Irmãos, coragem'),4:('Lar','Mãe, lar, paz'),5:('Inteligência','Filhos, criatividade'),6:('Conflito','Inimigos, doença'),7:('Parceria','Casamento, sócios'),8:('Transformação','Morte, renascimento'),9:('Fortuna','Pai, guru, sorte'),10:('Carreira','Profissão, status'),11:('Ganhos','Renda, amigos'),12:('Libertação','Perda, isolamento')},
  'zh': {1:('上升','自我、身体、身份'),2:('财富','金钱、言语、家庭'),3:('勇气','兄弟姐妹、勇气'),4:('家庭','母亲、家、安宁'),5:('智慧','子女、创造力'),6:('冲突','敌人、疾病'),7:('伴侣','婚姻、伙伴'),8:('转化','死亡、重生'),9:('命运','父亲、导师'),10:('事业','职业、地位'),11:('收获','收入、朋友'),12:('解脱','损失、孤独')},
  'ja': {1:('上昇','自己、身体'),2:('富','お金、話術、家族'),3:('勇気','兄弟、勇気'),4:('家庭','母、家、安らぎ'),5:('知性','子供、創造性'),6:('争い','敵、病気'),7:('パートナー','結婚、パートナー'),8:('変容','死、再生'),9:('幸運','父、師、運'),10:('天職','職業、地位'),11:('利得','収入、友人'),12:('解脱','喪失、悟り')},
}

DIGNITY_ED = {
  'en': {'exalted':('Exalted','Operating at highest potential.'),'own_sign':('Own Sign','At home. Functions naturally.'),'moolatrikona':('Moolatrikona','Near-peak efficiency.'),'friend_sign':('Friendly Sign','In ally\'s house. Receives support.'),'neutral_sign':('Neutral','Neither helped nor hindered.'),'enemy_sign':('Enemy Sign','In hostile territory. Extra effort needed.'),'debilitated':('Debilitated','Struggles but creates depth.')},
  'hi': {'exalted':('उच्च','सर्वोच्च क्षमता पर।'),'own_sign':('स्वराशि','अपने घर में। स्वाभाविक।'),'moolatrikona':('मूलत्रिकोण','लगभग चरम दक्षता।'),'friend_sign':('मित्र राशि','मित्र के घर में। सहयोग।'),'neutral_sign':('सम','न सहायता न बाधा।'),'enemy_sign':('शत्रु राशि','प्रतिकूल। अतिरिक्त प्रयास।'),'debilitated':('नीच','कठिनाई लेकिन गहराई।')},
  'es': {'exalted':('Exaltado','Máximo potencial.'),'own_sign':('Signo propio','En casa. Natural.'),'moolatrikona':('Moolatrikona','Eficiencia máxima.'),'friend_sign':('Signo amigo','En casa aliada.'),'neutral_sign':('Neutral','Ni ayudado ni obstaculizado.'),'enemy_sign':('Signo enemigo','Territorio hostil.'),'debilitated':('Debilitado','Lucha pero crea profundidad.')},
  'pt': {'exalted':('Exaltado','Potencial máximo.'),'own_sign':('Signo próprio','Em casa. Natural.'),'moolatrikona':('Moolatrikona','Eficiência máxima.'),'friend_sign':('Signo amigo','Na casa aliada.'),'neutral_sign':('Neutro','Nem ajudado nem impedido.'),'enemy_sign':('Signo inimigo','Território hostil.'),'debilitated':('Debilitado','Luta mas cria profundidade.')},
  'zh': {'exalted':('耀升','最高潜力运作。'),'own_sign':('庙旺','在家中。自然运作。'),'moolatrikona':('根本三角','接近巅峰效率。'),'friend_sign':('友好星座','在盟友家中。'),'neutral_sign':('中性','既无帮助也无阻碍。'),'enemy_sign':('敌对星座','在敌对领土。'),'debilitated':('落陷','挣扎但创造深度。')},
  'ja': {'exalted':('高揚','最高ポテンシャル。'),'own_sign':('定座','自分の家。自然に機能。'),'moolatrikona':('ムーラトリコーナ','ほぼ最高効率。'),'friend_sign':('友好星座','味方の家。'),'neutral_sign':('中立','助けも妨げもない。'),'enemy_sign':('敵対星座','敵地。余分な努力必要。'),'debilitated':('減衰','苦労するが深さを生む。')},
}

PLANET_IN_HOUSE_ED = {
  'en': {
    'Sun_1':'Natural authority. People notice you.','Sun_2':'Voice carries weight. Financial independence matters.','Sun_3':'Bold communication. Fight for beliefs.','Sun_4':'Inner peace through achievement.','Sun_5':'Creativity burns bright. Romance intense.','Sun_6':'Natural fighter. Competition and service.','Sun_7':'Find yourself through others.','Sun_8':'True power is invisible.','Sun_9':'Fortune and teachers come naturally.','Sun_10':'Built for visible achievement.','Sun_11':'Income grows through authority.','Sun_12':'Authority works behind scenes.',
    'Moon_1':'Emotions visible on your face.','Moon_2':'Financial security emotionally important.','Moon_3':'Mind restless, curious, communicating.','Moon_4':'Deep roots. Mother\'s influence profound.','Moon_5':'Emotional life rich and romantic.','Moon_6':'Process stress through your body.','Moon_7':'Deep emotional connection needed.','Moon_8':'Emotions run deep and private.','Moon_9':'Emotions tied to philosophy.','Moon_10':'Profession involves emotional intelligence.','Moon_11':'Satisfaction through friendships.','Moon_12':'Dreams vivid. Privacy essential.',
    'Mars_1':'Physical courage, sharp instinct.','Mars_2':'Speech sharp. Fight for financial security.','Mars_3':'Extraordinary willpower.','Mars_4':'Restlessness drives achievement.','Mars_5':'Sharp mind, competitive creativity.','Mars_6':'Defeat opposition naturally.','Mars_7':'Passion and conflict equally.','Mars_8':'Investigative power.','Mars_9':'Fight for your beliefs.','Mars_10':'Built for action — engineering, sports.','Mars_11':'Income through competition.','Mars_12':'Energy spent behind scenes.',
    'Mercury_1':'Quick-witted and communicative.','Mercury_2':'Business intelligence. Speech is your asset.','Mercury_3':'Writing, teaching, media amplified.','Mercury_4':'Intellectual peace. Education foundational.','Mercury_5':'Analytical power in intelligence.','Mercury_6':'Analyze and dismantle obstacles.','Mercury_7':'Attract intelligent partners.','Mercury_8':'Research, psychology, forensics.','Mercury_9':'Philosophy and foreign knowledge.','Mercury_10':'Communication is your profession.','Mercury_11':'Income through commerce.','Mercury_12':'Thinking happens in isolation.',
    'Jupiter_1':'Wisdom blesses the ascendant.','Jupiter_2':'Financial wisdom natural.','Jupiter_3':'Wise communication.','Jupiter_4':'Deeply auspicious. Inner peace.','Jupiter_5':'One of the best placements. Wisdom flows.','Jupiter_6':'Protects through wisdom.','Jupiter_7':'Spouse likely wise or spiritual.','Jupiter_8':'Protects during crisis.','Jupiter_9':'Most auspicious placement. Grace flows.','Jupiter_10':'Professional wisdom, ethical leadership.','Jupiter_11':'Income generous. Friendships meaningful.','Jupiter_12':'Spiritual depth. Foreign lands bring wisdom.',
    'Venus_1':'Beauty and charm grace the ascendant.','Venus_2':'Comfort through beauty and luxury.','Venus_3':'Artistic communication. Music and writing.','Venus_4':'Luxury, beautiful spaces, harmony.','Venus_5':'Deeply auspicious. Love and art flourish.','Venus_6':'Relationships carry friction.','Venus_7':'Marriage is central to your life.','Venus_8':'Intimacy deep and transformative.','Venus_9':'Love connected with philosophy.','Venus_10':'Success through aesthetics or diplomacy.','Venus_11':'Wealth through beauty and social connections.','Venus_12':'Pleasure in solitude. Devotion through beauty.',
    'Saturn_1':'Ages you beyond years. Best years later.','Saturn_2':'Money through hard work, not luck.','Saturn_3':'Extraordinary perseverance.','Saturn_4':'Tough foundations but unbreakable.','Saturn_5':'Joy delayed. Maturity with time.','Saturn_6':'You outlast every opponent.','Saturn_7':'Marriage delayed or serious partner.','Saturn_8':'Longevity but chronic patterns.','Saturn_9':'Philosophy earned, not inherited.','Saturn_10':'Powerful but slow. Success after 30.','Saturn_11':'Income delayed but permanent.','Saturn_12':'Deep inner life. Solitary growth.',
    'Rahu_1':'Intense, unconventional personality.','Rahu_2':'Unusual earning. Hypnotic speech.','Rahu_3':'Extraordinary ambition. Media, tech.','Rahu_4':'May live far from birthplace.','Rahu_5':'Sharp unconventional thinking.','Rahu_6':'Demolish opposition unconventionally.','Rahu_7':'Unusual or foreign partners.','Rahu_8':'Sudden changes. Occult knowledge.','Rahu_9':'Unorthodox spiritual views.','Rahu_10':'Intense ambition. Unconventional success.','Rahu_11':'Income through tech or foreign ties.','Rahu_12':'Vivid dreams. Foreign residence.',
    'Ketu_1':'Spiritual sensitivity natural.','Ketu_2':'Detach from family and money.','Ketu_3':'Quiet bravery. Intuitive communication.','Ketu_4':'Peace through spiritual surrender.','Ketu_5':'Intuitive brilliance. Detach from romance.','Ketu_6':'Opposition dissolves mysteriously.','Ketu_7':'Partner has past-life significance.','Ketu_8':'Natural psychic ability.','Ketu_9':'Already walked the spiritual path.','Ketu_10':'Success comes but you don\'t cling.','Ketu_11':'Few but spiritual friends.','Ketu_12':'Moksha placement. Awakening is purpose.',
  },
  'hi': {
    'Sun_1':'स्वाभाविक अधिकार। लोग ध्यान देते हैं।','Sun_2':'वाणी में वजन। आर्थिक स्वतंत्रता महत्वपूर्ण।','Sun_3':'निडर संवाद। विश्वास के लिए लड़ते हैं।','Sun_4':'उपलब्धि से शांति।','Sun_5':'रचनात्मकता तेज। प्रेम में तीव्रता।','Sun_6':'जन्मजात योद्धा।','Sun_7':'दूसरों से स्वयं को पाते हैं।','Sun_8':'असली शक्ति अदृश्य।','Sun_9':'भाग्य और गुरु स्वाभाविक।','Sun_10':'दृश्य उपलब्धि के लिए बने।','Sun_11':'अधिकार से आय।','Sun_12':'पर्दे के पीछे अधिकार।',
    'Moon_1':'भावनाएँ चेहरे पर।','Moon_2':'आर्थिक सुरक्षा भावनात्मक रूप से जरूरी।','Moon_3':'मन बेचैन, जिज्ञासु।','Moon_4':'गहरी जड़ें। माँ का प्रभाव गहरा।','Moon_5':'भावनात्मक जीवन समृद्ध।','Moon_6':'तनाव शरीर से गुजरता है।','Moon_7':'गहरे भावनात्मक जुड़ाव की जरूरत।','Moon_8':'भावनाएँ गहरी और निजी।','Moon_9':'भावनाएँ दर्शन से जुड़ी।','Moon_10':'पेशे में भावनात्मक बुद्धि।','Moon_11':'मित्रता से संतुष्टि।','Moon_12':'सपने स्पष्ट। एकांत जरूरी।',
    'Mars_1':'शारीरिक साहस, तेज प्रवृत्ति।','Mars_2':'वाणी तीखी। आर्थिक सुरक्षा के लिए लड़ते हैं।','Mars_3':'असाधारण इच्छाशक्ति।','Mars_4':'बेचैनी उपलब्धि चलाती है।','Mars_5':'तेज दिमाग, प्रतिस्पर्धी रचनात्मकता।','Mars_6':'श्रेष्ठ स्थान। विरोध स्वाभाविक रूप से हराते हैं।','Mars_7':'जुनून और संघर्ष बराबर।','Mars_8':'खोजी शक्ति।','Mars_9':'विश्वासों के लिए लड़ते हैं।','Mars_10':'कर्म के लिए बने।','Mars_11':'प्रतियोगिता से आय।','Mars_12':'ऊर्जा पर्दे के पीछे।',
    'Mercury_1':'बुद्धि से व्यक्तित्व।','Mercury_2':'व्यापारिक बुद्धि। वाणी संपत्ति।','Mercury_3':'लेखन, शिक्षण, मीडिया।','Mercury_4':'बौद्धिक शांति।','Mercury_5':'विश्लेषणात्मक शक्ति।','Mercury_6':'समस्या-समाधान में तेज।','Mercury_7':'बुद्धिमान साथी आकर्षित।','Mercury_8':'शोध, मनोविज्ञान।','Mercury_9':'दर्शन और विदेशी ज्ञान।','Mercury_10':'संवाद ही पेशा।','Mercury_11':'विचारों से जुड़ाव।','Mercury_12':'एकांत में सोचते हैं।',
    'Jupiter_1':'ज्ञान का आशीर्वाद।','Jupiter_2':'आर्थिक ज्ञान स्वाभाविक।','Jupiter_3':'बुद्धिमान संवाद।','Jupiter_4':'अत्यंत शुभ। आंतरिक शांति।','Jupiter_5':'श्रेष्ठ स्थान। ज्ञान बहता है।','Jupiter_6':'ज्ञान से रक्षा।','Jupiter_7':'जीवनसाथी बुद्धिमान।','Jupiter_8':'संकट में रक्षा।','Jupiter_9':'सबसे शुभ। कृपा बहती है।','Jupiter_10':'पेशेवर ज्ञान, नैतिक नेतृत्व।','Jupiter_11':'उदार आय। सार्थक मित्रता।','Jupiter_12':'आध्यात्मिक गहराई।',
    'Venus_1':'सौंदर्य और आकर्षण।','Venus_2':'सौंदर्य से समृद्धि।','Venus_3':'कलात्मक संवाद।','Venus_4':'विलासिता, सुंदर घर।','Venus_5':'अत्यंत शुभ। प्रेम और कला।','Venus_6':'रिश्तों में घर्षण।','Venus_7':'विवाह जीवन का केंद्र।','Venus_8':'अंतरंगता गहरी।','Venus_9':'प्रेम और दर्शन।','Venus_10':'सौंदर्य से सफलता।','Venus_11':'सामाजिक संबंधों से धन।','Venus_12':'एकांत में आनंद।',
    'Saturn_1':'उम्र से ज्यादा परिपक्व।','Saturn_2':'कड़ी मेहनत से पैसा।','Saturn_3':'असाधारण धैर्य।','Saturn_4':'कठिन लेकिन अटूट नींव।','Saturn_5':'खुशी में देरी।','Saturn_6':'हर विरोधी से आगे।','Saturn_7':'विवाह में देरी या गंभीर साथी।','Saturn_8':'दीर्घायु लेकिन पुरानी समस्याएँ।','Saturn_9':'दर्शन कमाना पड़ता है।','Saturn_10':'शक्तिशाली लेकिन धीमा।','Saturn_11':'आय में देरी लेकिन स्थायी।','Saturn_12':'गहरा आंतरिक जीवन।',
    'Rahu_1':'तीव्र, अपारंपरिक व्यक्तित्व।','Rahu_2':'असामान्य कमाई।','Rahu_3':'असाधारण महत्वाकांक्षा।','Rahu_4':'जन्मस्थान से दूर।','Rahu_5':'तेज अपारंपरिक सोच।','Rahu_6':'अपारंपरिक तरीकों से विरोध खत्म।','Rahu_7':'असामान्य या विदेशी साथी।','Rahu_8':'अचानक बदलाव। गूढ़ ज्ञान।','Rahu_9':'अपरंपरागत आध्यात्मिक दृष्टि।','Rahu_10':'तीव्र सांसारिक महत्वाकांक्षा।','Rahu_11':'तकनीक से आय।','Rahu_12':'स्पष्ट सपने। विदेश।',
    'Ketu_1':'शरीर से विरक्ति। आध्यात्मिक संवेदनशीलता।','Ketu_2':'परिवार और धन से विरक्ति।','Ketu_3':'शांत बहादुरी।','Ketu_4':'आध्यात्मिक समर्पण से शांति।','Ketu_5':'सहज प्रतिभा। प्रेम से विरक्ति।','Ketu_6':'विरोध रहस्यमय तरीके से समाप्त।','Ketu_7':'पूर्वजन्म का संबंध।','Ketu_8':'प्राकृतिक पारलौकिक क्षमता।','Ketu_9':'आध्यात्मिक मार्ग पहले ही तय।','Ketu_10':'सफलता आती है पर पकड़ नहीं।','Ketu_11':'आध्यात्मिक मित्र।','Ketu_12':'मोक्ष स्थान। आत्मजागृति।',
  },
}
# es/pt/zh/ja use English fallback for planet-in-house
for lang in ['es', 'pt', 'zh', 'ja']:
    PLANET_IN_HOUSE_ED[lang] = PLANET_IN_HOUSE_ED['en'].copy()

def get_planet_edu(planet, lang='en'):
    data = PLANET_EDUCATION.get(lang, PLANET_EDUCATION.get('en', {}))
    return data.get(planet, PLANET_EDUCATION.get('en', {}).get(planet, {}))

def get_house_ed(house, lang='en'):
    data = HOUSE_ED.get(lang, HOUSE_ED.get('en', {}))
    return data.get(house, HOUSE_ED.get('en', {}).get(house, ('', '')))

def get_planet_in_house(planet, house, lang='en'):
    key = f"{planet}_{house}"
    data = PLANET_IN_HOUSE_ED.get(lang, PLANET_IN_HOUSE_ED.get('en', {}))
    return data.get(key, PLANET_IN_HOUSE_ED.get('en', {}).get(key, ''))

def get_dignity_ed(dignity_type, lang='en'):
    data = DIGNITY_ED.get(lang, DIGNITY_ED.get('en', {}))
    return data.get(dignity_type, DIGNITY_ED.get('en', {}).get(dignity_type, ('', '')))
